version: '3.8'
services:

# Contenedor para la aplicacion web
  public-web:
    build: . # Construir la imagen desde el Dockerfile en el directorio actual.
    ports:
      - "8080:80" # Mapear el puerto 80 del contenedor al puerto 8080 del host.
    enviroment: # Declara las varibles de entorno necesarias para la conexión con Base de Datos
      DB_HOST: database
      DB_USER: user_web
      DB_PASSWORD: user_password
      DB_NAME: cooperativa
    depends_on:
     - database


# Contenedor para la base de datos MySQL
  database:
    image: mysql:8.0 # Usar MySQL versión 8.0.
    environment: # Variables de entorno para configurar MySQL
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cooperativa
      MYSQL_USER: user_web
      MYSQL_PASSWORD: user_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./source/backend/config/database/cooperativa.sql:/docker-entrypoint-initdb.d/init-users.sql